[package]
name = "risc0-examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "multiply"
path = "src/bin/multiply.rs"

[[bin]]
name = "zklogin"
path = "src/bin/zklogin.rs"


[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.3", default-features = false, features = ['std'] }
